import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, Check, CircleAlert } from "lucide-react";
import { EditorialPage, EditorialHero, SectionIntro, EditorialFAQ, EditorialLinks, EditorialDisclaimer, PageSchema } from "@/components/editorial/Editorial";
import { InsightExplorer } from "@/components/editorial/FeatureExplorers";
import styles from "@/components/editorial/Editorial.module.css";

const description = "Explore how MyCalAgent looks for associations across logged meals, water, schedules, and personal check-ins, and understand the limits of AI wellness observations.";
export const metadata: Metadata = { title: "AI Wellness Insights", description, alternates: { canonical: "https://www.mycalagent.com/ai-wellness-insights" }, openGraph: { title: "AI Wellness Insights", description, url: "https://www.mycalagent.com/ai-wellness-insights" } };
const faq = [
  { question: "What is an AI wellness insight?", answer: "It is an informational observation about your logged routines. AI can look for associations across meals, water, schedules, and personal check-ins. An observation does not establish what caused a change in how you feel." },
  { question: "How do meal photos become part of an insight?", answer: "AI estimates foods, portions, and nutrition from a meal photo. You review and correct the entry before saving it. Those saved logs can then add context to observations over time." },
  { question: "Does more logging guarantee better insights?", answer: "No. Consistency can add context, but an observation still depends on data quality, completeness, and the limits of the analysis. Some records may not support a meaningful pattern." },
  { question: "What about caffeine, alcohol, and other habits?", answer: "Beverage and habit entries can provide additional context when recorded. A summary cannot account for everything happening in your life or determine which habit caused an outcome." },
  { question: "Are these examples my results?", answer: "No. The examples on this page are illustrative. They do not use your personal data, represent measured user outcomes, or guarantee the availability of any particular insight." },
  { question: "Can I use an insight for a medical decision?", answer: "No. MyCalAgent is not a medical device or healthcare provider. AI estimates and observations may be inaccurate or incomplete. Consult a qualified healthcare professional for medical decisions." },
];

export default function AIWellnessInsightsPage() {
  return <><PageSchema path="/ai-wellness-insights" title="AI Wellness Insights" description={description} faq={faq} /><EditorialPage>
    <EditorialHero label="AI INSIGHTS" title={"AI wellness\ninsights."} description="Your meals and routines, considered together. A starting point for reflection, with room for uncertainty." image="/ai-insights-editorial.png" alt="Illustrative still life of breakfast, a notebook, a phone, and a glass of water" href="#observations" action="Explore an observation" />
    <div className={styles.strip}><div className={styles.wrap}><span>BASED ON YOUR LOGS</span><span>ASSOCIATIONS, NOT CAUSES</span><span>WELLNESS, NOT MEDICAL ADVICE</span></div></div>
    <section className={`${styles.wrap} ${styles.section}`}><SectionIntro eyebrow="AI WELLNESS INTELLIGENCE" title="From everyday details to reflection." description="Three ways to think about AI's role, with your review and judgment at the center." /><div className={styles.intelligenceGrid}>{[
      { image: "/intelligence-meal-recognition.png", title: "Recognize the details.", body: "AI assists with identifying foods and estimating nutrition. Your corrections add details a photo cannot reveal.", alt: "Concept illustration of ingredient recognition layers above a meal" },
      { image: "/intelligence-daily-context.png", title: "Bring context together.", body: "Meal logs, water entries, schedules, and check-ins contribute different perspectives on a recorded day.", alt: "Concept illustration of meal, water, time, and journal records grouped together" },
      { image: "/intelligence-reflection.png", title: "Make room to reflect.", body: "Plain-language observations can prompt questions. They cannot establish causes or replace your own judgment.", alt: "Concept illustration of journal records beside a plain-language observation represented by a quotation mark" },
    ].map((item, index) => <figure key={item.title}><div className={styles.photo}><Image src={item.image} alt={item.alt} fill sizes="(max-width:640px) 90vw, 380px" /></div><figcaption><span className={styles.eyebrow}>0{index + 1} / AI CONCEPT</span><h3>{item.title}</h3><p>{item.body}</p></figcaption></figure>)}</div><p className={styles.photoNote}>AI-generated concept illustrations. These are not app screenshots or measured results.</p></section>
    <section id="observations" className={`${styles.wrap} ${styles.section}`}><SectionIntro eyebrow="A PATTERN IS A QUESTION WORTH ASKING" title={"A little context.\nA different perspective."} description="Explore examples of how everyday records might be discussed, including what those records cannot tell you." /><InsightExplorer /></section>
    <section className={`${styles.cool} ${styles.section}`}><div className={`${styles.wrap} ${styles.split}`}><div><SectionIntro eyebrow="FROM ENTRIES TO OBSERVATIONS" title={"The detail behind\nthe bigger picture."} description="Meal photos become reviewed logs. Water entries, eating windows, and personal check-ins add context over time." /><p className={styles.sampleBottom}>An occasional entry is only a small part of a day. Missing records, changing routines, and imperfect estimates all affect what can be observed.</p><Link href="/how-mycalagent-works" className={styles.textLink}>How MyCalAgent works<ArrowUpRight size={18} /></Link></div><figure><div className={styles.photo}><Image src="/upcoming-glucose.png" alt="Illustrative photo of a meal, blank notebook, and phone, representing everyday records" fill sizes="(max-width:640px) 90vw, 550px" /></div><figcaption className={styles.photoNote}>Illustrative lifestyle imagery. No personal data shown.</figcaption></figure></div></section>
    <section className={`${styles.wrap} ${styles.section}`}><SectionIntro eyebrow="INTELLIGENCE WITH LIMITS" title="Clarity includes what we don't know." /><div className={styles.boundary}><div><h3>What observations can offer</h3><ul><li><Check size={18} />A summary of recorded habits and routines.</li><li><Check size={18} />A way to notice repetition and variation.</li><li><Check size={18} />Questions to reflect on alongside your own experience.</li></ul></div><div><h3>What they cannot establish</h3><ul><li><CircleAlert size={18} />That one food or habit caused an outcome.</li><li><CircleAlert size={18} />A diagnosis, treatment, or medication decision.</li><li><CircleAlert size={18} />A guaranteed result, or a complete picture of your health.</li></ul></div></div></section>
    <EditorialFAQ items={faq} /><section className={`${styles.rose} ${styles.section}`}><div className={`${styles.wrap} ${styles.feedback}`}><SectionIntro eyebrow="ASK BETTER QUESTIONS" title="Curiosity, with perspective." description="Read about our approach to evidence and the limits of AI before treating any observation as an answer." /><Link href="/ai-disclaimer" className={styles.button}>Read the AI disclaimer<ArrowUpRight size={18} /></Link></div></section><EditorialLinks links={[["Features", "/features"], ["Blog", "/blog"], ["Research", "/research"], ["Editorial Policy", "/editorial-policy"], ["Wellness patterns", "/features/wellness-pattern-recognition"]]} /><EditorialDisclaimer />
  </EditorialPage></>;
}
